-- MySQL Script generated by MySQL Workbench
-- qua 06 out 2021 23:23:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema veggi
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `veggi` ;

-- -----------------------------------------------------
-- Schema veggi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `veggi` ;
USE `veggi` ;

-- -----------------------------------------------------
-- Table `veggi`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veggi`.`user` (
      `user_id` INT NOT NULL AUTO_INCREMENT,
      `user_name` VARCHAR(45) NULL,
      PRIMARY KEY (`user_id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veggi`.`task_status_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veggi`.`task_status_type` (
      `task_status_id` INT NOT NULL,
      `task_status_description` VARCHAR(45) NULL,
      PRIMARY KEY (`task_status_id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veggi`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veggi`.`task` (
      `task_id` INT NOT NULL AUTO_INCREMENT,
      `task_description` VARCHAR(60) NULL,
      `task_status_id` INT NULL,
      `user_id` INT NULL,
      PRIMARY KEY (`task_id`),
      INDEX `fk_task_user_id_idx` (`user_id` ASC) VISIBLE,
      INDEX `fk_task_status_id_idx` (`task_status_id` ASC) VISIBLE,
      CONSTRAINT `fk_task_user_id`
          FOREIGN KEY (`user_id`)
              REFERENCES `veggi`.`user` (`user_id`)
              ON DELETE NO ACTION
              ON UPDATE NO ACTION,
      CONSTRAINT `fk_task_status_id`
          FOREIGN KEY (`task_status_id`)
              REFERENCES `veggi`.`task_status_type` (`task_status_id`)
              ON DELETE NO ACTION
              ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO task_status_type (task_status_id, task_status_description) VALUES(1, "Feito");
INSERT INTO task_status_type (task_status_id, task_status_description) VALUES(2, "Pendente");